### ISSUE TITLE
The paper referenced in the desc. and README is removed

### ISSUE THREAD

**Issue by FredrikAugust** [andreafioraldi/leakyleak#1]
As the title states, the paper which you are referencing ("return-to-csu: A New Method to Bypass 64-bit Linux ASLR") has been removed from the website you've linked to, and moved here: https://i.blackhat.com/briefings/asia/2018/asia-18-Marco-return-to-csu-a-new-method-to-bypass-the-64-bit-Linux-ASLR-wp.pdf.

**Comment by andreafioraldi** [comment]
ok ty
